-- Enable UUID extension if needed (though we use int8 for IDs here to match old schema, generic serial is fine)
-- Actually, for Supabase it's better to use `bigint generated by default as identity`

-- 1. Sources Table (Agent 1)
create table if not exists sources (
  id bigint primary key generated by default as identity,
  url text not null unique,
  type text not null default 'website',
  name text not null,
  added_at timestamptz not null default now(),
  last_scanned timestamptz,
  enabled boolean not null default true,  -- Toggle to enable/disable individual sources
  last_error text,  -- Store last error message if scan failed
  jobs_found_last_scan int default 0  -- Track jobs found in last scan
);

-- 2. Jobs Table (All Agents)
create table if not exists jobs (
  id bigint primary key generated by default as identity,
  source_id bigint references sources(id) on delete set null,
  agent_id text not null, -- 'agent1', 'agent2', 'agent3'
  title text not null,
  company text,
  location text,
  url text,
  description text,
  date_posted date,  -- actual posting date from the source
  discovered_at timestamptz not null default now(),
  content_hash text not null unique,
  source_url text,  -- For Agent 2/3 context
  source_name text,  -- For Agent 2/3 context (e.g. "Lever", "JSearch")
  hidden boolean not null default false,  -- User can hide jobs from view
  hidden_at timestamptz  -- Timestamp when job was hidden
);

-- 3. Scan History Table
create table if not exists scan_history (
  id bigint primary key generated by default as identity,
  started_at timestamptz not null,
  completed_at timestamptz,
  total_sources int default 0,
  total_jobs_found int default 0,
  total_new_jobs int default 0,
  status text default 'running',
  details text
);

-- Create index for faster pagination and filtering
create index if not exists jobs_date_posted_idx on jobs (date_posted desc nulls last);
create index if not exists jobs_discovered_at_idx on jobs (discovered_at desc);
create index if not exists jobs_agent_id_idx on jobs (agent_id);
create index if not exists jobs_hidden_idx on jobs (hidden);
create index if not exists sources_enabled_idx on sources (enabled);
